export const revisionConflict = '26';
export const healthReasons = Object.freeze({
  outcome_unclaimed: 'Outcome unclaimed', destination_gone: 'Destination gone', poisoned: 'Actor poisoned',
  declared: 'Actor declared failure', parameter_denied: 'Parameter denied', transport_terminal: 'Transport ended',
  approval_required: 'Approval required', diverged: 'Replay diverged', endpoint_gone: 'Endpoint gone',
  interpreter_fault: 'Interpreter failed', peer: 'Peer unavailable', source_failure: 'Source failed', capacity: 'Capacity reached',
  activation_failed: 'Activation failed', activation_witness_missing: 'Activation witness missing', activation_registration_failed: 'Activation registration failed',
  recovery_refused: 'Not recovered after restart', kernel_fault: 'Stopped by a kernel fault',
  harness_unbound: 'Waiting for its harness binding',
  harness_unusable: 'Waiting: its bound harness program cannot run',
});
const labels = new Map(Object.entries({
  unobserved: 'Health unobserved',
  not_standing: 'Not standing: no pipeline stands',
  accepted: 'Changes committed',
  ORGANIZE_NOTHING_TO_MOVE: 'Nothing to organize',
  COMBINATOR_WIRE_REQUIRED: 'Place it on a wire',
  CONNECT_PORT_REQUIRED: 'No port to connect',
  Resumed: 'Pipeline resumed', Paused: 'Pipeline paused',
  UNJUDGED: 'No verdict before commit',
  SDK_PROGRAM_COPIED: 'SDK program copied.', CLIPBOARD_UNAVAILABLE: 'The clipboard is not available.',
  SDK_PROGRAM_UNAVAILABLE: 'The SDK program could not be loaded.',
  FIXTURE_HAS_NO_AUTHORING_FOLD: 'Connect to a project to read its SDK program.',
  'authoring.generator.complete-log-required': 'The SDK program needs the complete declaration history.',
  'authoring.generator.pin-required': 'The SDK program needs its authoring environment.',
  'authoring.generator.combinator-actor-not-supported': 'A wire step cannot be written as an actor in the SDK program.',
  'authoring.generator.scope-not-supported': 'This scope cannot be written as an SDK program.',
  'authoring.generator.operations-not-supported': 'This export declaration cannot be written as an SDK program.',
  'authoring.generator.unsupported-command': 'A declaration cannot be written as an SDK program.',
  'authoring.generator.spec-set-mismatch': 'The declarations and SDK use different specification sets.',
  'authoring.generator.constructor-unresolved': 'An actor has no available SDK constructor.',
  'authoring.generator.constructor-not-normalized': 'An actor’s configuration cannot be reproduced by its SDK constructor.',
  'authoring.generator.invalid-command': 'A declaration cannot be read to generate the SDK program.',
  'authoring.generator.incomplete-epoch': 'The declaration history contains an unfinished edit.',
  'authoring.generator.annotation-not-spellable': 'An annotation cannot be written in the SDK program.',
  'authoring.generator.presentation-not-spellable': 'An actor’s presentation cannot be written in the SDK program.',
  'authoring.generator.invalid-template': 'A stored template cannot be written as an SDK program.',
  'authoring.generator.compacted-log-required': 'The SDK program needs the current declarations folded from the history.',
  'authoring.prepass.replicator-policy': 'The key path, capacity and idle lifetime do not make a replicator policy',
  'authoring.prepass.template-inlet-count': 'A replicator’s cell takes exactly one inlet: wire one input of the selected actors from outside',
  'authoring.template.unsupported-command': 'A replicator’s cell cannot hold a container’s scope',
  'authoring.template.foreign-reference': 'An export mount names both selected actors and others, so it cannot go into the cell',
  EDIT_BUSY: 'An edit is pending or its receipt is unknown', EDIT_PENDING: 'Commit or discard the open candidate',
  EDIT_LOST_COMMITTED: 'The edit whose answer was lost was committed',
  EDIT_LOST_NOT_COMMITTED: 'The edit whose answer was lost was not committed',
  EDIT_LOST_UNKNOWN: 'The edit whose answer was lost has ended; whether it committed could not be read',
  EDIT_UNAVAILABLE: 'Edit receipt unavailable', EDIT_NOT_VALIDATED: 'No validated candidate', EDIT_NOT_OPEN: 'No open candidate',
  INLET_INJECTION_UNAVAILABLE: 'Sending is unavailable: no request is bound to this port',
  EDIT_BASELINE_UNAVAILABLE: 'The observed authoring revision or environment is unavailable',
  DELIVERY_NOT_EXECUTED: 'This delivery is not executed: the inlet admits no arrival',
  EDGE_PREPROCESS_SHAPE: 'Preprocessing must be an ordered list',
  EDGE_PREPROCESS_STEP: 'Preprocessing kind is not supported',
  EDGE_PREPROCESS_CONFIG: 'Preprocessing configuration is invalid',
  ACTOR_EXISTS: 'That actor name already exists in this scope', ADMISSION_UNAVAILABLE: 'Actor admission did not return a declaration',
  CREATE_BY_GROUPING: 'Select actors, then Group, to make this container',
  CREATE_INPUTS_UNAVAILABLE: 'The daemon publishes no creation settings for this actor',
  CREATE_INPUTS_UNREAD: 'Creation settings are not read yet',
  PROJECT_EXISTS: 'A folder with that name is already there; choose a new name for the project',
  PROJECT_CREATE_FAILED: 'The project folder could not be created there',
  ACTOR_REPLACED: 'Another author replaced an existing actor',
  CONFIG_VALUE_INVALID: 'Enter a value of the existing field type',
  FIELD_NAME_INVALID: 'Each field needs its own name',
  FIELD_LIMIT_REACHED: 'No more fields can be added',
  CHOICE_NOT_PUBLISHED: 'This value is not among the choices the daemon publishes for this field',
  CONFIG_EDITOR_UNAVAILABLE: 'Typed value editor unavailable',
  ACTOR_ICON_UNAVAILABLE: 'This actor has no icon of its own',
  COMBINATOR_ICON_UNAVAILABLE: 'This step has no icon of its own',
  VIEW_KIND_UNREGISTERED: 'This view is not available; the basic view is shown',
  VIEW_ACTOR_TYPE_UNREGISTERED: 'This actor type has no view of its own; the basic view is shown',
  CIRCULAR_VIEW_CONFIG_INVALID: 'This actor’s view settings do not fit the view vocabulary; the view draws without them',
  VIEW_KIND_DUPLICATE: 'View kind is already registered',
  UNDO_EMPTY: 'Nothing to undo', REDO_EMPTY: 'Nothing to redo',
  UNDO_ALREADY_RESTORED: 'Already as before; nothing committed',
  UNDO_KEY_EDITED: 'Another author changed it since; left as they set it',
  UNDO_TARGET_GONE: 'What it stood on is gone; not set back',
  OUTLET_UNWIRED: 'Not wired',
  EMISSION_UNOBSERVED: 'No emission on screen',
  EMISSION_NOT_NUMERIC: 'Last value is not a number',
  ARRIVAL_UNOBSERVED: 'No arrival on screen',
  MAILBOX_DEPTH_UNOBSERVED: 'Not read yet',
  MAILBOX_DEPTH_UNANSWERED: 'No answer from the receiving actor',
  MAILBOX_DEPTH_UNRECORDED: 'Not recorded; shown only for now',
  INLET_UNWIRED: 'Connect a wire to edit this inlet’s processing',
  BODY_UNRECORDED: 'This arrival was recorded without a body',
  PORT_UNRECORDED: 'This arrival names no port',
  LOCAL_INDEX_UNRECORDED: 'This arrival has no recorded actor-local index',
  NOTIFICATION_UNOBSERVED: 'No notification on screen',
  SUPPRESSION_UNRECORDED: 'How many were suppressed is not recorded',
  TURN_UNOBSERVED: 'No turn on screen',
  TURN_PREPROCESSED: 'This turn went through the wire’s steps, and the value they gave the actor is not read yet',
  TURN_WIRE_UNREAD: 'This turn came over a wire this screen does not hold, so the value the actor received is not shown',
  INSTANCE_SCOPE_UNAVAILABLE: 'This instance’s scope is not available on the canvas',
  INSTANCE_TRANSITION_UNTIMED: 'Instance transitions have no recorded time to open in history',
  INSTANCE_PHASE_UNOBSERVED: 'No actor phase has been observed in this instance',
  INSTANCE_PHASE_Draining: 'An actor was draining',
  INSTANCE_PHASE_AdmissionClosed: 'An actor’s admission was closed',
  INSTANCE_PHASE_Terminated: 'An actor was terminated',
  INSTANCE_PHASE_Prepared: 'An actor was prepared',
  INSTANCE_PHASE_Activated: 'An actor was activated',
  INSTANCE_PHASE_Restarted: 'An actor was restarted',
  INSTANCE_PHASE_ConfigRestarted: 'An actor was restarted after a configuration change',
  INSTANCE_PHASE_Abandoned: 'An actor was abandoned',
  INSTANCE_PHASE_ResumeDenied: 'An actor’s resumption was denied',
  INSTANCE_PHASE_ConfigApplied: 'An actor’s configuration was applied',
  STEP_UNOBSERVED: 'No step on screen',
  RESULT_UNOBSERVED: 'No result on screen',
  VALUE_NOT_TEXT: 'These bytes are not text, so their length is shown',
  RESULT_VALUE_NOT_BYTES: 'The result is not bytes',
  TASK_MEANING_UNDECLARED: 'The turn declares no meaning',
  TOOLS_UNDECLARED: 'No tool is declared',
  TOOL_RESULT_UNOBSERVED: 'No tool result on screen',
  OUTCOME_CAUSE_UNRECORDED: 'This result names no arrival that caused it',
  OUTCOME_CAUSE_UNREAD: 'The arrival that caused this result is not in what this screen has read',
  OUTCOME_CAUSE_AMBIGUOUS: 'More than one arrival matches the one that caused this result',
  TOOL_CALL_PREPROCESSED: 'The call behind this result came over a wire with steps and is recorded before them, so which tool ran is not shown',
  TOOL_CALL_UNREAD: 'The call behind this result came over a wire this screen does not hold, so which tool ran is not shown',
  TOOL_CAUSE_NOT_CALL: 'The arrival that caused this result is not a tool call, so it names no tool',
  WRITE_UNOBSERVED: 'No write on screen',
  WRITE_COMPLETION_UNRECORDED: 'Whether the write finished is not recorded',
  PORTS_UNAVAILABLE: 'The daemon did not answer this actor’s ports',
  UNDECLARED: 'Not declared',
  TIME_UNRECORDED: 'No recorded time',
  INCIDENT_TIME_UNAVAILABLE: 'No recorded time is available for these incidents',
  DENSITY_UNREAD: 'Arrivals before the first reading are not counted',
  TIMELINE_UNREAD: 'The recorded summary of this range is not read yet',
  CLOCK_REGRESSIONS: 'Recorded arrival times moved backwards',
  processing: 'Processing', actor_declared: 'Actor declared failure',
  ...healthReasons,
  'activation.missing_actor': 'This actor is missing from the revision that started it',
  'activation.unexpected_actor_type': 'This actor type cannot be started this way',
  'activation.config_fold': 'The settings could not be read',
  'activation.unexpected_requirements': 'The capabilities this actor needs differ from its type’s',
  'activation.canonical_spec_mismatch': 'This actor’s declaration differs from its type’s',
  'activation.bundle_actor_mismatch': 'The grants handed over belong to another actor',
  'activation.unexpected_source_arm': 'This actor type cannot be started as a source',
  'activation.stale_instance_grant': 'The instance grant handed over belongs to another actor',
  'activation.authored_projection': 'This actor’s declaration could not be read from its revision',
  'activation.requirement_resolution': 'The capabilities this actor needs could not be resolved',
  'activation.capability_denied': 'A capability this actor needs was not granted',
  'activation.instance_admission': 'The template’s instance was not admitted',
  'activation.missing_activation_witness': 'No record shows this actor was started',
  'activation.config_admission': 'This actor’s configuration was refused when it started',
  'activation.effect_executor_registration': 'This actor’s effect could not be set up',
  'activation.journal_unavailable': 'The journal could not open this actor’s records',
  'source.glob_unpublished_syntax': 'The glob may use only * and ** as patterns',
  'source.glob_mixed_globstar': 'In the glob, ** must stand alone between slashes',
  'agent_harness.program_not_executable': 'The harness program can’t run. Fix it, then bind the harness again in Harnesses.',
  ATTACHING: 'Attaching to the selected state directory',
  SOCKET_MISSING: 'No daemon is running for this state', CONNECT_FAILED: 'No daemon is running for this state',
  BRIDGE_UNAVAILABLE: 'Desktop connection bridge unavailable',
  CLI_UNAVAILABLE: 'The circular command is missing or cannot be executed beside Circular.app; start the daemon for this directory by hand (QUICKSTART §3)',
  ROOT_MODE_MISMATCH: 'The state directory must be owner-only; chmod 700 it',
  CLI_STATUS_UNAVAILABLE: 'The circular command did not return daemon status',
  CLI_START_FAILED: 'The circular command could not start the daemon',
  CLI_STOP_FAILED: 'The circular command could not stop the daemon',
  DAEMON_NOT_ANSWERING: 'The daemon is not answering; use File → Reconnect',
  DAEMON_ANSWERING: 'Daemon running and answering',
  RECENT_READ_FAILED: 'Recent state locations could not be read', RECENT_INVALID: 'Recent state locations are invalid',
  RECENT_WRITE_FAILED: 'Recent state locations could not be saved',
  STATE_REQUIRED: 'No project is open; start one with New project or Open project on Projects',
  PROJECT_NOT_OPEN: 'Not open in this window',
  PREFERENCE_UNSAVED: 'This device could not save the preference',
  HARNESS_NOT_HELD: 'Saved; used when the pipeline starts',
  HARNESS_NOT_SAVED: 'Not saved in this project',
  HARNESS_HELD_OTHER: 'The running pipeline uses another program',
  READ_UNAVAILABLE: 'Reading unavailable', QUERY_RESULT_REQUIRED: 'Query response unavailable', QUERY_PAGE_INVALID: 'Invalid query page',
  folded_from: 'Observed cut out of range; the whole fold was answered',
  QUERY_INCOMPLETE: 'Incomplete query', QUERY_REJECTED: 'Query rejected',
  PORT_UNANSWERED: 'The actor’s port answer does not name this wired port',
  RECORD_DECODER_UNAVAILABLE: 'Record contents cannot be read',
  ASSEMBLY_STATE_UNREPORTED: 'The daemon does not report open assemblies',
  APPROVAL_CAUSE_UNRECORDED: 'This request names no recorded arrival, so its call cannot be shown',
  APPROVAL_CAUSE_UNREAD: 'The arrival that called this request could not be read',
  PERMISSION_ALLOWED: 'Allowed', PERMISSION_DENIED: 'Denied',
  APPROVAL_POLICY_REQUIRED: 'Approval is required', APPROVAL_POLICY_NONE: 'Approval is not required',
  APPROVAL_POLICY_UNREADABLE: 'This approval policy could not be read',
  SUBSCRIPTION_REJECTED: 'The daemon refused to send live updates',
  SUBSCRIPTION_UNANSWERED: 'The daemon did not confirm live updates', SUBSCRIPTION_ENDED: 'Live updates ended',
  SESSION_CLOSED: 'The daemon session closed',
  boundary_disagrees_with_derivation: 'The scope’s boundary ports do not match the wires that cross it',
  stale_boundary_generation: 'The scope’s boundary changed after it was read',
  boundary_leaf_unresolved: 'A boundary port names an actor or port that is not there',
  CANVAS_EMPTY: 'Nothing is deployed in this scope',
  INSPECTOR_EMPTY: 'Nothing selected',
  REQUESTS_EMPTY: 'No pending requests.',
  OUTPUTS_EMPTY: 'No declared views',
  PROJECTS_EMPTY: 'No projects',
  PALETTE_NO_MATCH: 'No matches',
  JOURNAL_EMPTY: 'No arrivals in this selection',
  SELECTION_RECORDS_PENDING: 'Reading this selection’s arrivals…',
  FORM_FIELDS_UNDECLARED: 'No field is declared',
  OUTLETS_UNDECLARED: 'No outlet is declared',
  INLET_PROCESSING_EMPTY: 'Values arrive unchanged',
  INSTANCES_EMPTY: 'No current instances',
  INSTANCE_TRANSITIONS_EMPTY: 'No instance transition is recorded',
  HARNESSES_UNBOUND: 'No harness is bound in this project',
  BOUNDARY_PORTS_UNDECLARED: 'No boundary port is declared',
  HARNESSES_UNREAD: 'Harnesses are not read',
  CAPABILITIES_UNREQUIRED: 'No capability is required',
  CONFIG_SLOTS_UNDECLARED: 'This actor has no settings',
  HARNESSES_UNDECLARED: 'No harness is named in this project',
  CONFIG_FILE_ABSENT: 'There is no config.toml in this folder; Finder shows the folder',
}));
const sharedLine = new Map(Object.entries({
  '1': 'Declaration or request rejected', '2': 'Target unresolved',
  '17': 'Request refused: its key was still open on this session',
  '29': 'Read closed before its end',
  '30': 'Not recovered after restart; Resume retries it',
  '19': 'The read result could not be made', '20': 'No pipeline stands', '22': 'Activation failed', '23': 'Arrival recording stopped', '24': 'Revision adoption failed',
  '31': 'The actor ended before it answered',
  [revisionConflict]: 'Another edit landed first',
  '6401': 'This daemon has no harness by that name', '6402': 'The program is not an absolute path',
  '6403': 'The program does not exist or is not an executable file',
}));
export const systemOutcomeReason = code => ({ code: String(code), label: sharedLine.get(String(code)) ?? String(code) });
const spaces = Object.freeze({
  Declaration: { labels: sharedLine, refused: 'Edit refused' },
  Query: { labels: sharedLine, refused: 'Read refused' },
  Subscription: { labels: sharedLine, refused: 'Subscription refused' },
  EventInjection: { labels: sharedLine, refused: 'Injection refused' },
  ReplayControl: { labels: sharedLine, refused: 'Replay refused' },
  LedgerTransition: { labels: sharedLine, refused: 'Decision refused' },
  Lifecycle: { labels: new Map(), refused: 'Pause or resume was refused' },
});
const number = value => Number.isInteger(value) || typeof value === 'bigint' ? value
  : typeof value?.value === 'bigint' ? value.value : undefined;
export const inSpace = (space, code) => number(code) === undefined ? code : { space, code: number(code) };
export const codeText = code => spaces[code?.space] ? reason(code).code : String(code);
export const noDaemon = new Set(['SOCKET_MISSING', 'CONNECT_FAILED']);
export const noProject = new Set(['STATE_REQUIRED']);
const clientFailures = {
  EXHAUSTED: 'Too many requests are open on this connection', REQUEST_TIMED_OUT: 'The daemon did not answer in time',
  QUERY_TIMED_OUT: 'The daemon did not answer the read in time', SUBSCRIPTION_TIMED_OUT: 'The daemon did not open the subscription in time',
  MESSAGE_TOO_LARGE: 'The message is larger than the connection admits', SEND_FAILED: 'A request could not be sent to the daemon',
  TRANSPORT_FAILED: 'The connection to the daemon failed', STREAM_CLOSED: 'The connection to the daemon is closed',
  STREAM_FAILED: 'Reading from the daemon failed', STREAM_TRUNCATED: 'The daemon’s answer was cut off',
  SLOT_NOT_LIVE: 'The answer came for a request that is no longer open',
  ROOT_MISSING: 'The state directory is missing', ROOT_NOT_ABSOLUTE: 'The state directory is not an absolute path',
  ROOT_NOT_DIRECTORY: 'The state path is not a directory', ROOT_IS_SYMLINK: 'The state directory is a symbolic link, so it is not used',
  ROOT_OWNER_MISMATCH: 'The state directory belongs to another user', ROOT_UNREADABLE: 'The state directory could not be inspected',
  SOCKET_NOT_SOCKET: 'The daemon’s socket path is not a socket', SOCKET_IS_SYMLINK: 'The daemon’s socket is a symbolic link, so it is not used',
  SOCKET_MODE_MISMATCH: 'The daemon’s socket is open to other users, so it is not used',
  SOCKET_OWNER_MISMATCH: 'The daemon’s socket belongs to another user', SOCKET_UNREADABLE: 'The daemon’s socket could not be inspected',
  SOCKET_IDENTITY_CHANGED: 'The daemon’s socket was replaced while connecting', SOCKET_NAME_INVALID: 'The socket name is not one file name',
  UID_UNAVAILABLE: 'This system does not report the user the connection is checked against',
  ESTABLISHMENT_REJECTED: 'The daemon refused this connection', ESTABLISHMENT_UNEXPECTED: 'The daemon answered the connection with something else',
  ESTABLISHED_INCOMPLETE: 'The daemon’s answer to the connection could not be read', ESTABLISHED_SHAPE: 'The daemon’s answer to the connection could not be read',
  UNSUPPORTED_VERSION: 'The daemon speaks another protocol version',
  RESULT_UNEXPECTED: 'The daemon answered with something other than what was asked',
  INJECT_ANSWER_UNEXPECTED: 'The daemon answered the send with something else',
  SUBSCRIPTION_ANSWER_UNEXPECTED: 'The daemon answered the subscription with something else',
  ENVELOPE_MALFORMED: 'The daemon’s answer could not be read', FRAME_SHAPE: 'The daemon’s answer could not be read',
  FRAME_ARM_UNKNOWN: 'The daemon’s answer could not be read', FRAME_ORIGIN_UNKNOWN: 'The daemon’s answer could not be read',
  FRAME_FOLDED_MISSING: 'The daemon’s answer could not be read', FRAME_PENDING_AFTER: 'The daemon’s answer could not be read',
  FRAME_BODY_TOO_LARGE: 'The daemon’s answer is larger than the connection admits',
  FRAGMENTED_CONTROL: 'The daemon’s answer could not be read', EMPTY_FRAGMENT: 'The daemon’s answer could not be read',
  SEGMENT_UNKNOWN: 'The daemon’s answer could not be read', UNEXPECTED_SEGMENT: 'The daemon’s answer could not be read',
  ENDING_SHAPE: 'The daemon’s answer could not be read', ENDING_REASON_UNKNOWN: 'The daemon ended a stream for a reason this app does not know',
  OPERATION_UNKNOWN: 'The daemon’s answer could not be read', CREDIT_PENDING_AFTER: 'The daemon’s answer could not be read',
  CHANNEL_WIDTH: 'The daemon’s answer could not be read', MINOR_WIDTH: 'The daemon’s answer could not be read',
  REPLAY_END_BODY: 'The daemon’s answer could not be read',
  SNAPSHOT_REJECTED: 'The daemon refused to read the declarations', SNAPSHOT_PARTIAL: 'The declarations were read only in part',
  SNAPSHOT_REVISION: 'The declarations came without their revision', QUERY_ANCHOR_MIXED: 'The declarations changed while they were read',
  SUBSCRIPTION_CLOSED: 'Live updates are closed', SUBSCRIPTION_CREDIT_REJECTED: 'The daemon refused more live updates',
  REPLAY_LENS_ENDED: 'The replay has ended',
  DECLARATION_REJECTED: 'The daemon refused the declaration', BEGIN_REJECTED: 'The daemon refused to open the edit',
  VALIDATE_REJECTED: 'The daemon refused the edit when it checked it', COMMIT_REJECTED: 'The daemon refused to commit the edit',
  ABORT_REJECTED: 'The daemon refused to discard the edit',
  INJECT_KEY_REUSED: 'The send reused a key the daemon still holds', INJECT_MOUNT_REQUIRED: 'Sending needs a request bound to this port',
  BEGIN_SCOPE: 'This app asked for an edit the client does not take', COMMAND_SEQUENCE: 'This app asked for an edit the client does not take',
  COMMAND_UNEXPECTED: 'This app asked for an edit the client does not take',
  CEILINGS_MISSING: 'This app made a request the client does not take', CORRELATION_ALREADY_LIVE: 'This app made a request the client does not take',
  CORRELATION_ID_INVALID: 'This app made a request the client does not take', CORRELATION_NOT_LIVE: 'This app made a request the client does not take',
  MAXIMUM_LIVE_INVALID: 'This app made a request the client does not take', MAXIMUM_MESSAGE_BYTES_INVALID: 'This app made a request the client does not take',
  MAXIMUM_PENDING_FRAMES_INVALID: 'This app made a request the client does not take', PAGE_LIMIT: 'This app made a request the client does not take',
  VERB_UNKNOWN: 'This app made a request the client does not take', REPLAY_VERB: 'This app made a request the client does not take',
  INJECT_ORIGIN_EMPTY: 'This app made a request the client does not take', INJECT_ORIGIN_REQUIRED: 'This app made a request the client does not take',
  INJECT_SESSION_INVALID: 'This app made a request the client does not take', SUBSCRIPTION_CREDIT_REQUIRED: 'This app made a request the client does not take',
  SUBSCRIPTION_DISCIPLINE: 'This app made a request the client does not take', SUBSCRIPTION_LENS: 'This app made a request the client does not take',
  SUBSCRIPTION_SESSION_INVALID: 'This app made a request the client does not take',
};
for (const [code, sentence] of Object.entries(clientFailures)) if (!labels.has(code)) labels.set(code, sentence);
const severities = new Map([
  ...['accepted', 'Resumed', 'Paused', 'SDK_PROGRAM_COPIED'].map(code => [code, 'success']),
  ...['ORGANIZE_NOTHING_TO_MOVE', 'UNDO_EMPTY', 'REDO_EMPTY', 'UNDO_ALREADY_RESTORED', 'UNDO_KEY_EDITED',
    'UNDO_TARGET_GONE', 'TIME_UNRECORDED', 'ACTOR_REPLACED', 'ATTACHING',
  ].map(code => [code, 'notice']),
]);
export const severity = code => severities.get(reason(code).code) ?? 'failure';
export function reason(code) {
  const space = spaces[code?.space], spaced = space ? number(code.code) : undefined;
  if (spaced !== undefined) {
    const label = space.labels.get(String(spaced));
    return label ? { code: String(spaced), label } : { code: `${code.space} ${spaced}`, label: space.refused };
  }
  const value = code && typeof code === 'object' && 'value' in code ? code.value : code && typeof code === 'object' && 'code' in code ? code.code : code;
  const label = labels.get(String(value));
  if (label) return { code: String(value), label };
  if (number(value) !== undefined) return { code: String(number(value)), label: 'Refusal number read without its verb' };
  return { code: 'UNRECOGNIZED_REASON', label: 'Unrecognized reason code' };
}
export const reasonText = code => {
  const value = reason(code);
  return value.code === 'UNRECOGNIZED_REASON' ? codeText(code) : value.label;
};
export const refusalCode = refusal => typeof refusal?.at === 'string' && reason(refusal.at).code !== 'UNRECOGNIZED_REASON'
  ? refusal.at : refusal?.code ?? 'EDIT_UNAVAILABLE';
export const NOT_STANDING = 'not_standing';
export const EMPTY = 'empty';
export const healthLabel = state => ({ running:'Alive', waiting:'Alive', stopped:'Dead', failed: 'Failed', backpressure: 'Backpressure', [NOT_STANDING]: 'Not standing' })[state] ?? reason('unobserved').label;
export const healthState = state => ({running:'alive',waiting:'alive',backpressure:'alive',failed:'dead',stopped:'dead',[NOT_STANDING]:NOT_STANDING})[state] ?? 'unobserved';
export const lifeLabel = state => ({alive:'Alive',dead:'Dead',[NOT_STANDING]:'Not standing',[EMPTY]:'No actors yet'})[state] ?? reason('unobserved').label;
export const healthText = node => healthState(node.health) === 'unobserved'
  ? reasonText('unobserved')
  : node.health === 'waiting' && node.issue ? reasonText(node.issue.code)
  : `${healthLabel(node.health)}${node.issue ? ` · ${reasonText(node.issue.code)}` : ''}`;
export const detailText = (detail, field = detail?.slot) => !detail ? ''
  : detail.slot == null ? reasonText(detail.code) : `${field}: ${reasonText(detail.code)}`;
const lifecycles = {
  running: 'Running',
  stopped: 'Paused',
  activation_failed: 'Activation failed',
  revision_adoption_failed: 'Revision adoption failed',
  recovery_failed: 'Recovery failed',
};
export const lifecycleLabel = state => lifecycles[state] ?? 'No runtime observed';
