[package]
name = "cli"
version = "0.1.0-alpha.1"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
sha2 = "=0.10.9"
circular-core = { path = "../core" }
circular-protocol = { package = "protocol", path = "../protocol" }
circular-transport = { package = "transport", path = "../transport" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "circular-client"
path = "src/bin/circular-client.rs"
